# Generated by Django 5.2.15 on 2026-06-28 19:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NutrientDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("unit", models.CharField(max_length=24)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("energy", "Energy"),
                            ("macro", "Macronutrient"),
                            ("micro", "Micronutrient"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "ordering": ("category", "name"),
            },
        ),
        migrations.CreateModel(
            name="FoodNutrientValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount_per_100g",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "amount_per_serving",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "serving_size_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("serving_label", models.CharField(blank=True, max_length=120)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("lab", "Lab analysis"),
                            ("verified_database", "Verified database"),
                            ("import", "Imported database"),
                            ("barcode", "Barcode provider"),
                            ("user", "User entered"),
                            ("ai_estimate", "AI estimate"),
                            ("recipe_calculated", "Recipe calculated"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_name", models.CharField(max_length=255)),
                ("source_reference", models.CharField(blank=True, max_length=512)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrient_values",
                        to="foods.fooditem",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_values",
                        to="nutrition.nutrientdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ("food", "nutrient"),
                "indexes": [
                    models.Index(
                        fields=["food", "nutrient"],
                        name="nutrition_f_food_id_4b8648_idx",
                    ),
                    models.Index(
                        fields=["source_type", "source_name"],
                        name="nutrition_f_source__dc9245_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("food", "nutrient", "source_type", "source_name"),
                        name="unique_nutrition_value_source",
                    )
                ],
            },
        ),
    ]
