# Generated by Django 5.2.15 on 2026-06-28 20:33

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("unit", models.CharField(max_length=24)),
                (
                    "nutrient_group",
                    models.CharField(
                        choices=[
                            ("macro", "Macro"),
                            ("vitamin", "Vitamin"),
                            ("mineral", "Mineral"),
                            ("fatty_acid", "Fatty acid"),
                            ("amino_acid", "Amino acid"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("recommended_daily_unit", models.CharField(blank=True, max_length=24)),
                ("aliases", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ("nutrient_group", "name"),
                "indexes": [
                    models.Index(fields=["code"], name="nutrition_n_code_075e69_idx"),
                    models.Index(
                        fields=["nutrient_group", "name"],
                        name="nutrition_n_nutrien_93d47d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NutritionDataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("USDA_FDC", "USDA FoodData Central"),
                            ("OPEN_FOOD_FACTS", "Open Food Facts"),
                            ("IFCT_2017", "Indian Food Composition Tables 2017"),
                            ("INDB", "Indian Nutrient Databank"),
                            ("USER_CUSTOM", "User custom"),
                            ("AI_ESTIMATE", "AI estimate"),
                            ("MANUAL_ADMIN", "Manual admin"),
                        ],
                        max_length=32,
                    ),
                ),
                ("license_name", models.CharField(blank=True, max_length=180)),
                ("license_url", models.URLField(blank=True)),
                ("citation", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("update_frequency", models.CharField(blank=True, max_length=120)),
                (
                    "reliability_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
                "indexes": [
                    models.Index(
                        fields=["source_type", "is_active"],
                        name="nutrition_n_source__c3adbc_idx",
                    ),
                    models.Index(fields=["name"], name="nutrition_n_name_c0495e_idx"),
                ],
            },
        ),
    ]
