# Generated by Django 5.2.15 on 2026-06-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0002_nutrient_nutritiondatasource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutritiondatasource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("USDA_FDC", "USDA FoodData Central"),
                    ("OPEN_FOOD_FACTS", "Open Food Facts"),
                    ("IFCT_2017", "Indian Food Composition Tables 2017"),
                    ("INDB", "Indian Nutrient Databank"),
                    ("USER_CUSTOM", "User custom"),
                    ("AI_ESTIMATE", "AI estimate"),
                    ("MANUAL_ADMIN", "Manual admin"),
                    ("MANUAL_ADMIN_SAMPLE", "Manual admin sample"),
                ],
                max_length=32,
            ),
        ),
    ]
