# Generated by Django 5.2.15 on 2026-06-28 19:51

import uuid

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
            ],
            options={
                "verbose_name_plural": "food categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(db_index=True, max_length=255)),
                ("brand", models.CharField(blank=True, max_length=255)),
                ("barcode", models.CharField(blank=True, db_index=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                ("cuisine", models.CharField(blank=True, max_length=80)),
                ("region", models.CharField(blank=True, max_length=80)),
                ("is_indian_food", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "default_serving_size_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("default_serving_label", models.CharField(blank=True, max_length=120)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("system", "System curated"),
                            ("user", "User entered"),
                            ("import", "Imported database"),
                            ("barcode", "Barcode provider"),
                            ("ai_assisted", "AI assisted"),
                        ],
                        default="user",
                        max_length=32,
                    ),
                ),
                ("source_name", models.CharField(blank=True, max_length=255)),
                ("source_reference", models.CharField(blank=True, max_length=512)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="foods",
                        to="foods.foodcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means shared public food. Non-null foods are isolated to user_id.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "indexes": [
                    models.Index(
                        fields=["user", "name"], name="foods_foodi_user_id_d92a49_idx"
                    ),
                    models.Index(
                        fields=["is_public", "name"],
                        name="foods_foodi_is_publ_b7b00c_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["normalized_name"],
                        name="food_name_trgm_idx",
                        opclasses=("gin_trgm_ops",),
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("barcode", ""), _negated=True),
                        fields=("user", "barcode"),
                        name="unique_food_barcode_per_user",
                    )
                ],
            },
        ),
    ]
