# Generated by Django 5.2.15 on 2026-06-28 20:33

import uuid

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0001_initial"),
        ("nutrition", "0002_nutrient_nutritiondatasource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("canonical_name", models.CharField(max_length=255)),
                ("brand_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("generic", "Generic"),
                            ("branded", "Branded"),
                            ("restaurant", "Restaurant"),
                            ("recipe", "Recipe"),
                            ("user_custom", "User custom"),
                        ],
                        default="generic",
                        max_length=32,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=180)),
                ("country_code", models.CharField(default="IN", max_length=2)),
                ("language_code", models.CharField(default="en", max_length=12)),
                ("barcode", models.CharField(blank=True, db_index=True, max_length=64)),
                ("serving_description", models.CharField(blank=True, max_length=160)),
                (
                    "default_serving_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "data_quality_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("search_text", models.TextField(blank=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means shared catalog food. Non-null foods are scoped by user.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_foods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="foods",
                        to="nutrition.nutritiondatasource",
                    ),
                ),
            ],
            options={
                "ordering": ("canonical_name",),
            },
        ),
        migrations.CreateModel(
            name="FoodAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias", models.CharField(max_length=255)),
                ("language_code", models.CharField(default="en", max_length=12)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="foods.food",
                    ),
                ),
            ],
            options={
                "ordering": ("alias",),
            },
        ),
        migrations.CreateModel(
            name="FoodDataImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("rows_processed", models.PositiveIntegerField(default=0)),
                ("rows_created", models.PositiveIntegerField(default=0)),
                ("rows_updated", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_jobs",
                        to="nutrition.nutritiondatasource",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FoodNutrient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount_per_100g",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "derivation_method",
                    models.CharField(
                        choices=[
                            ("lab", "Lab"),
                            ("label", "Label"),
                            ("calculated", "Calculated"),
                            ("estimated", "Estimated"),
                            ("user_entered", "User entered"),
                            ("ai_estimated", "AI estimated"),
                        ],
                        default="estimated",
                        max_length=32,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrients",
                        to="foods.food",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="food_values",
                        to="nutrition.nutrient",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="food_nutrient_values",
                        to="nutrition.nutritiondatasource",
                    ),
                ),
            ],
            options={
                "ordering": ("food", "nutrient"),
            },
        ),
        migrations.CreateModel(
            name="FoodServing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("serving_name", models.CharField(max_length=160)),
                ("grams", models.DecimalField(decimal_places=2, max_digits=8)),
                ("household_quantity", models.CharField(blank=True, max_length=120)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servings",
                        to="foods.food",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_default", "serving_name"),
            },
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                fields=["canonical_name"], name="foods_food_canonic_65a67a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                fields=["created_by", "canonical_name"],
                name="foods_food_created_93a35a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                fields=["source", "external_id"], name="foods_food_source__ad553f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="food_search_vector_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_text"],
                name="food_search_text_trgm_idx",
                opclasses=("gin_trgm_ops",),
            ),
        ),
        migrations.AddConstraint(
            model_name="food",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode", ""), _negated=True),
                fields=("barcode",),
                name="unique_food_barcode_when_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="food",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("source", "external_id"),
                name="unique_food_source_external_id",
            ),
        ),
        migrations.AddIndex(
            model_name="foodalias",
            index=models.Index(fields=["alias"], name="foods_fooda_alias_4fa10a_idx"),
        ),
        migrations.AddIndex(
            model_name="foodalias",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["alias"],
                name="food_alias_trgm_idx",
                opclasses=("gin_trgm_ops",),
            ),
        ),
        migrations.AddConstraint(
            model_name="foodalias",
            constraint=models.UniqueConstraint(
                fields=("food", "alias", "language_code"),
                name="unique_food_alias_language",
            ),
        ),
        migrations.AddIndex(
            model_name="fooddataimportjob",
            index=models.Index(
                fields=["source", "status"], name="foods_foodd_source__7fecef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fooddataimportjob",
            index=models.Index(
                fields=["checksum"], name="foods_foodd_checksu_b20434_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foodnutrient",
            index=models.Index(
                fields=["food", "nutrient"], name="foods_foodn_food_id_3f1448_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foodnutrient",
            index=models.Index(
                fields=["source", "derivation_method"],
                name="foods_foodn_source__ecf920_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="foodnutrient",
            constraint=models.UniqueConstraint(
                fields=("food", "nutrient", "source", "derivation_method"),
                name="unique_food_nutrient_source_derivation",
            ),
        ),
        migrations.AddIndex(
            model_name="foodserving",
            index=models.Index(
                fields=["food", "is_default"], name="foods_foods_food_id_6d6421_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="foodserving",
            constraint=models.UniqueConstraint(
                fields=("food", "serving_name"), name="unique_food_serving_name"
            ),
        ),
    ]
