# Generated by Django 5.2.15 on 2026-06-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_food_foodalias_fooddataimportjob_foodnutrient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="allergens",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="food",
            name="ingredients_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="food",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="food",
            name="region",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
