# Generated by Django 5.2.15 on 2026-06-29 12:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0004_favoritefood"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroceryList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Grocery list", max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("planned_for", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="GroceryListItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                ("unit", models.CharField(default="serving", max_length=32)),
                ("is_checked", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        default="manual",
                        help_text="manual, recipe, low_pantry, or coach_suggestion.",
                        max_length=32,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grocery_list_items",
                        to="foods.food",
                    ),
                ),
                (
                    "grocery_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="foods.grocerylist",
                    ),
                ),
            ],
            options={
                "ordering": ("is_checked", "sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="PantryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("unit", models.CharField(default="serving", max_length=32)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In stock"),
                            ("low", "Low"),
                            ("out", "Out"),
                            ("expired", "Expired"),
                        ],
                        default="in_stock",
                        max_length=16,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pantry_items",
                        to="foods.food",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("expiry_date", "food__canonical_name"),
            },
        ),
        migrations.AddIndex(
            model_name="grocerylist",
            index=models.Index(
                fields=["user", "status", "planned_for"],
                name="foods_groce_user_id_6762e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="grocerylistitem",
            index=models.Index(
                fields=["grocery_list", "is_checked"],
                name="foods_groce_grocery_e3c4bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="grocerylistitem",
            index=models.Index(fields=["food"], name="foods_groce_food_id_f993b9_idx"),
        ),
        migrations.AddIndex(
            model_name="pantryitem",
            index=models.Index(
                fields=["user", "stock_status"], name="foods_pantr_user_id_26b5b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pantryitem",
            index=models.Index(
                fields=["user", "expiry_date"], name="foods_pantr_user_id_8274d9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pantryitem",
            constraint=models.UniqueConstraint(
                fields=("user", "food", "location"),
                name="unique_pantry_food_location_per_user",
            ),
        ),
    ]
