# Generated by Django 5.2.16 on 2026-07-31 17:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_existing_custom_foods(apps, schema_editor):
    Food = apps.get_model("foods", "Food")
    CustomFoodProfile = apps.get_model("foods", "CustomFoodProfile")
    CustomFoodVersion = apps.get_model("foods", "CustomFoodVersion")
    field_map = {
        "calories": "calories_kcal",
        "protein_g": "protein_g",
        "carbs_g": "carbs_g",
        "fat_g": "fat_g",
        "fiber_g": "fiber_g",
        "sugar_g": "sugar_g",
        "sodium_mg": "sodium_mg",
    }
    foods = Food.objects.filter(food_type="user_custom", created_by__isnull=False)
    for food in foods.iterator():
        serving_weight = food.default_serving_g or Decimal("100")
        values = {}
        for nutrient_value in food.nutrients.select_related("nutrient").all():
            field = field_map.get(nutrient_value.nutrient.code)
            if field:
                amount = nutrient_value.amount_per_100g * serving_weight / Decimal(
                    "100"
                )
                values[field] = str(amount.quantize(Decimal("0.001")))
        status = "confirmed" if values else "draft"
        protein = Decimal(values.get("protein_g", "0"))
        carbs = Decimal(values.get("carbs_g", "0"))
        fat = Decimal(values.get("fat_g", "0"))
        calculated_calories = (protein * 4) + (carbs * 4) + (fat * 9)
        CustomFoodProfile.objects.create(
            user_id=food.created_by_id,
            food_id=food.id,
            status=status,
            serving_quantity=Decimal("1"),
            serving_unit="serving",
            serving_weight_g=serving_weight,
            estimation_method="manual_entry" if values else "none",
            confirmed_nutrients=values,
            confidence_score=Decimal("0.5000") if values else Decimal("0"),
            calculated_calories_kcal=calculated_calories if values else None,
            confirmed_at=food.created_at if values else None,
        )
        CustomFoodVersion.objects.create(
            user_id=food.created_by_id,
            food_id=food.id,
            version=1,
            event="legacy_imported",
            status=status,
            snapshot={
                "status": status,
                "confirmed_nutrients": values,
                "migration_note": "Backfilled from existing user custom food.",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0008_food_completeness_score_food_dataset_release_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFoodProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("estimate_ready", "Estimate ready"),
                            ("needs_review", "Needs review"),
                            ("confirmed", "Confirmed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                (
                    "serving_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                ("serving_unit", models.CharField(default="serving", max_length=32)),
                (
                    "serving_weight_g",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "estimation_method",
                    models.CharField(
                        choices=[
                            ("none", "Not estimated"),
                            ("database_matches", "Trusted database matches"),
                            ("ingredient_sum", "Ingredient nutrition sum"),
                            ("manual_entry", "Manual user entry"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                (
                    "original_estimated_nutrients",
                    models.JSONField(blank=True, default=dict),
                ),
                ("estimated_nutrients", models.JSONField(blank=True, default=dict)),
                ("estimated_range", models.JSONField(blank=True, default=dict)),
                ("confirmed_nutrients", models.JSONField(blank=True, default=dict)),
                ("reference_foods", models.JSONField(blank=True, default=list)),
                ("ingredients", models.JSONField(blank=True, default=list)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("user_corrections", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "calculated_calories_kcal",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("version_number", models.PositiveIntegerField(default=1)),
                (
                    "food",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_profile",
                        to="foods.food",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="foods_custo_user_id_f8f92a_idx"
                    ),
                    models.Index(
                        fields=["user", "updated_at"],
                        name="foods_custo_user_id_d31900_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomFoodVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("event", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("estimate_ready", "Estimate ready"),
                            ("needs_review", "Needs review"),
                            ("confirmed", "Confirmed"),
                            ("archived", "Archived"),
                        ],
                        max_length=24,
                    ),
                ),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_versions",
                        to="foods.food",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-version",),
                "indexes": [
                    models.Index(
                        fields=["user", "food", "version"],
                        name="foods_custo_user_id_fe3af3_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("food", "version"), name="unique_custom_food_version"
                    )
                ],
            },
        ),
        migrations.RunPython(
            backfill_existing_custom_foods,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
