from django.core.management.base import BaseCommand

from foods.importers import (
    create_import_job,
    finish_import_job,
    get_manual_sample_source,
    import_json_food_records,
    seed_core_reference_data,
)
from foods.models import Food


POPULAR_FOODS = [
    {
        "canonical_name": "Chicken breast, raw, skinless",
        "external_id": "POPULAR-001",
        "country_code": "US",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["raw chicken breast", "skinless chicken breast"],
        "nutrients": {
            "calories": "120.0000",
            "protein_g": "22.5000",
            "carbs_g": "0.0000",
            "fat_g": "2.6000",
            "sodium_mg": "45.0000",
        },
    },
    {
        "canonical_name": "Chicken breast, grilled",
        "external_id": "POPULAR-002",
        "country_code": "US",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["grilled chicken breast", "grilled chicken"],
        "nutrients": {
            "calories": "165.0000",
            "protein_g": "31.0000",
            "carbs_g": "0.0000",
            "fat_g": "3.6000",
            "sodium_mg": "74.0000",
        },
    },
    {
        "canonical_name": "Rotisserie chicken breast",
        "external_id": "POPULAR-003",
        "country_code": "US",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["rotisserie chicken", "roast chicken breast"],
        "nutrients": {
            "calories": "165.0000",
            "protein_g": "31.0000",
            "carbs_g": "0.0000",
            "fat_g": "3.6000",
            "sodium_mg": "350.0000",
        },
    },
    {
        "canonical_name": "Egg whites, boiled",
        "external_id": "POPULAR-004",
        "country_code": "US",
        "serving_description": "1 large egg white",
        "default_serving_g": "33.00",
        "verified": False,
        "aliases": ["boiled egg whites", "egg white"],
        "nutrients": {
            "calories": "52.0000",
            "protein_g": "10.9000",
            "carbs_g": "0.7000",
            "fat_g": "0.2000",
            "sodium_mg": "166.0000",
        },
    },
    {
        "canonical_name": "Brown rice, cooked",
        "external_id": "POPULAR-005",
        "country_code": "US",
        "serving_description": "1 cup cooked",
        "default_serving_g": "195.00",
        "verified": False,
        "aliases": ["cooked brown rice", "brown rice"],
        "nutrients": {
            "calories": "112.0000",
            "protein_g": "2.3000",
            "carbs_g": "23.5000",
            "fat_g": "0.8000",
            "fiber_g": "1.8000",
        },
    },
    {
        "canonical_name": "Basmati rice, cooked",
        "external_id": "POPULAR-006",
        "country_code": "IN",
        "serving_description": "1 cup cooked",
        "default_serving_g": "160.00",
        "verified": False,
        "aliases": ["basmati rice", "cooked basmati"],
        "nutrients": {
            "calories": "121.0000",
            "protein_g": "3.5000",
            "carbs_g": "25.2000",
            "fat_g": "0.4000",
            "fiber_g": "0.4000",
        },
    },
    {
        "canonical_name": "Roti",
        "external_id": "POPULAR-007",
        "country_code": "IN",
        "serving_description": "1 medium roti",
        "default_serving_g": "40.00",
        "verified": False,
        "aliases": ["roti", "phulka", "chapati"],
        "nutrients": {
            "calories": "260.0000",
            "protein_g": "8.7000",
            "carbs_g": "46.4000",
            "fat_g": "4.5000",
            "fiber_g": "6.7000",
        },
    },
    {
        "canonical_name": "Paratha, plain",
        "external_id": "POPULAR-008",
        "country_code": "IN",
        "serving_description": "1 paratha",
        "default_serving_g": "80.00",
        "verified": False,
        "aliases": ["plain paratha", "parantha"],
        "nutrients": {
            "calories": "326.0000",
            "protein_g": "7.0000",
            "carbs_g": "45.0000",
            "fat_g": "13.0000",
            "fiber_g": "5.0000",
        },
    },
    {
        "canonical_name": "Naan, plain",
        "external_id": "POPULAR-009",
        "country_code": "IN",
        "serving_description": "1 naan",
        "default_serving_g": "90.00",
        "verified": False,
        "aliases": ["naan", "plain naan"],
        "nutrients": {
            "calories": "310.0000",
            "protein_g": "9.0000",
            "carbs_g": "56.0000",
            "fat_g": "5.0000",
            "fiber_g": "2.5000",
        },
    },
    {
        "canonical_name": "Moong dal, cooked",
        "external_id": "POPULAR-010",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "180.00",
        "verified": False,
        "aliases": ["moong dal", "yellow dal"],
        "nutrients": {
            "calories": "105.0000",
            "protein_g": "7.0000",
            "carbs_g": "18.0000",
            "fat_g": "0.4000",
            "fiber_g": "7.0000",
        },
    },
    {
        "canonical_name": "Rajma curry",
        "external_id": "POPULAR-011",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "200.00",
        "verified": False,
        "aliases": ["rajma", "kidney bean curry"],
        "nutrients": {
            "calories": "127.0000",
            "protein_g": "7.0000",
            "carbs_g": "19.0000",
            "fat_g": "2.5000",
            "fiber_g": "6.0000",
        },
    },
    {
        "canonical_name": "Chole curry",
        "external_id": "POPULAR-012",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "200.00",
        "verified": False,
        "aliases": ["chole", "chickpea curry", "chana masala"],
        "nutrients": {
            "calories": "164.0000",
            "protein_g": "8.9000",
            "carbs_g": "27.4000",
            "fat_g": "2.6000",
            "fiber_g": "7.6000",
        },
    },
    {
        "canonical_name": "Paneer tikka",
        "external_id": "POPULAR-013",
        "country_code": "IN",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["paneer tikka", "grilled paneer"],
        "nutrients": {
            "calories": "278.0000",
            "protein_g": "18.0000",
            "carbs_g": "5.0000",
            "fat_g": "21.0000",
            "calcium_mg": "220.0000",
        },
    },
    {
        "canonical_name": "Idli",
        "external_id": "POPULAR-014",
        "country_code": "IN",
        "serving_description": "1 idli",
        "default_serving_g": "40.00",
        "verified": False,
        "aliases": ["idli", "steamed rice cake"],
        "nutrients": {
            "calories": "146.0000",
            "protein_g": "4.5000",
            "carbs_g": "30.0000",
            "fat_g": "0.7000",
            "fiber_g": "1.5000",
        },
    },
    {
        "canonical_name": "Dosa, plain",
        "external_id": "POPULAR-015",
        "country_code": "IN",
        "serving_description": "1 dosa",
        "default_serving_g": "97.00",
        "verified": False,
        "aliases": ["dosa", "plain dosa"],
        "nutrients": {
            "calories": "168.0000",
            "protein_g": "3.9000",
            "carbs_g": "29.0000",
            "fat_g": "3.7000",
            "fiber_g": "1.1000",
        },
    },
    {
        "canonical_name": "Sambar",
        "external_id": "POPULAR-016",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "200.00",
        "verified": False,
        "aliases": ["sambar", "sambhar"],
        "nutrients": {
            "calories": "65.0000",
            "protein_g": "3.5000",
            "carbs_g": "11.0000",
            "fat_g": "1.2000",
            "fiber_g": "3.5000",
        },
    },
    {
        "canonical_name": "Poha",
        "external_id": "POPULAR-017",
        "country_code": "IN",
        "serving_description": "1 plate",
        "default_serving_g": "180.00",
        "verified": False,
        "aliases": ["poha", "flattened rice poha"],
        "nutrients": {
            "calories": "180.0000",
            "protein_g": "3.5000",
            "carbs_g": "32.0000",
            "fat_g": "4.5000",
            "fiber_g": "2.0000",
        },
    },
    {
        "canonical_name": "Upma",
        "external_id": "POPULAR-018",
        "country_code": "IN",
        "serving_description": "1 plate",
        "default_serving_g": "180.00",
        "verified": False,
        "aliases": ["upma", "rava upma"],
        "nutrients": {
            "calories": "190.0000",
            "protein_g": "5.0000",
            "carbs_g": "30.0000",
            "fat_g": "5.5000",
            "fiber_g": "2.5000",
        },
    },
    {
        "canonical_name": "Chicken biryani",
        "external_id": "POPULAR-019",
        "country_code": "IN",
        "serving_description": "1 plate",
        "default_serving_g": "300.00",
        "verified": False,
        "aliases": ["chicken biryani", "biryani"],
        "nutrients": {
            "calories": "185.0000",
            "protein_g": "10.0000",
            "carbs_g": "22.0000",
            "fat_g": "6.0000",
            "fiber_g": "1.5000",
        },
    },
    {
        "canonical_name": "Salmon, cooked",
        "external_id": "POPULAR-020",
        "country_code": "US",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["salmon", "cooked salmon"],
        "nutrients": {
            "calories": "206.0000",
            "protein_g": "22.0000",
            "carbs_g": "0.0000",
            "fat_g": "12.0000",
            "sodium_mg": "59.0000",
        },
    },
    {
        "canonical_name": "Tuna, canned in water",
        "external_id": "POPULAR-021",
        "country_code": "US",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["tuna", "canned tuna"],
        "nutrients": {
            "calories": "116.0000",
            "protein_g": "25.5000",
            "carbs_g": "0.0000",
            "fat_g": "0.8000",
            "sodium_mg": "247.0000",
        },
    },
    {
        "canonical_name": "Greek yogurt, plain",
        "external_id": "POPULAR-022",
        "country_code": "US",
        "serving_description": "1 cup",
        "default_serving_g": "170.00",
        "verified": False,
        "aliases": ["greek yogurt", "plain greek yogurt"],
        "nutrients": {
            "calories": "73.0000",
            "protein_g": "10.0000",
            "carbs_g": "3.9000",
            "fat_g": "1.9000",
            "calcium_mg": "115.0000",
        },
    },
    {
        "canonical_name": "Quinoa, cooked",
        "external_id": "POPULAR-023",
        "country_code": "US",
        "serving_description": "1 cup cooked",
        "default_serving_g": "185.00",
        "verified": False,
        "aliases": ["quinoa", "cooked quinoa"],
        "nutrients": {
            "calories": "120.0000",
            "protein_g": "4.4000",
            "carbs_g": "21.3000",
            "fat_g": "1.9000",
            "fiber_g": "2.8000",
        },
    },
    {
        "canonical_name": "Sweet potato, boiled",
        "external_id": "POPULAR-024",
        "country_code": "US",
        "serving_description": "1 medium",
        "default_serving_g": "130.00",
        "verified": False,
        "aliases": ["sweet potato", "boiled sweet potato"],
        "nutrients": {
            "calories": "76.0000",
            "protein_g": "1.4000",
            "carbs_g": "17.7000",
            "fat_g": "0.1000",
            "fiber_g": "2.5000",
        },
    },
    {
        "canonical_name": "Broccoli, cooked",
        "external_id": "POPULAR-025",
        "country_code": "US",
        "serving_description": "1 cup",
        "default_serving_g": "156.00",
        "verified": False,
        "aliases": ["broccoli", "steamed broccoli"],
        "nutrients": {
            "calories": "35.0000",
            "protein_g": "2.4000",
            "carbs_g": "7.2000",
            "fat_g": "0.4000",
            "fiber_g": "3.3000",
            "vitamin_c_mg": "64.9000",
        },
    },
    {
        "canonical_name": "Mango",
        "external_id": "POPULAR-026",
        "country_code": "IN",
        "serving_description": "1 cup pieces",
        "default_serving_g": "165.00",
        "verified": False,
        "aliases": ["mango", "aam"],
        "nutrients": {
            "calories": "60.0000",
            "protein_g": "0.8000",
            "carbs_g": "15.0000",
            "fat_g": "0.4000",
            "fiber_g": "1.6000",
            "sugar_g": "13.7000",
        },
    },
    {
        "canonical_name": "Orange",
        "external_id": "POPULAR-027",
        "country_code": "US",
        "serving_description": "1 medium",
        "default_serving_g": "131.00",
        "verified": False,
        "aliases": ["orange", "santra"],
        "nutrients": {
            "calories": "47.0000",
            "protein_g": "0.9000",
            "carbs_g": "11.8000",
            "fat_g": "0.1000",
            "fiber_g": "2.4000",
            "vitamin_c_mg": "53.2000",
        },
    },
    {
        "canonical_name": "Peanuts, roasted",
        "external_id": "POPULAR-028",
        "country_code": "US",
        "serving_description": "1 oz",
        "default_serving_g": "28.00",
        "verified": False,
        "aliases": ["peanuts", "roasted peanuts", "moongfali"],
        "nutrients": {
            "calories": "585.0000",
            "protein_g": "24.4000",
            "carbs_g": "21.5000",
            "fat_g": "49.7000",
            "fiber_g": "8.0000",
        },
    },
    {
        "canonical_name": "Coffee with milk, no sugar",
        "external_id": "POPULAR-029",
        "country_code": "IN",
        "serving_description": "1 cup",
        "default_serving_g": "180.00",
        "verified": False,
        "aliases": ["milk coffee", "coffee"],
        "nutrients": {
            "calories": "32.0000",
            "protein_g": "1.7000",
            "carbs_g": "2.4000",
            "fat_g": "1.8000",
            "sugar_g": "2.5000",
        },
    },
    {
        "canonical_name": "Tea with milk, no sugar",
        "external_id": "POPULAR-030",
        "country_code": "IN",
        "serving_description": "1 cup",
        "default_serving_g": "180.00",
        "verified": False,
        "aliases": ["chai", "milk tea", "tea"],
        "nutrients": {
            "calories": "35.0000",
            "protein_g": "1.6000",
            "carbs_g": "2.8000",
            "fat_g": "1.7000",
            "sugar_g": "2.7000",
        },
    },
]


class Command(BaseCommand):
    help = "Seed a larger local friends-beta food catalog for daily testing."

    def handle(self, *args, **options):
        seed_core_reference_data()
        source = get_manual_sample_source()
        job = create_import_job(source, file_name="seed_popular_foods")
        result = import_json_food_records(
            POPULAR_FOODS,
            source,
            default_food_type=Food.FoodType.GENERIC,
        )
        finish_import_job(job, result)
        self.stdout.write(
            self.style.SUCCESS(
                "Seeded popular foods: "
                f"{result.rows_created} created, {result.rows_updated} updated, "
                f"{len(result.errors or [])} errors."
            )
        )
