from django.core.management.base import BaseCommand

from foods.importers import (
    create_import_job,
    finish_import_job,
    get_manual_sample_source,
    import_json_food_records,
    seed_core_reference_data,
)
from foods.models import Food


POPULAR_FOODS = [
    {
        "canonical_name": "Chicken breast, raw, skinless",
        "external_id": "POPULAR-001",
        "country_code": "US",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["raw chicken breast", "skinless chicken breast"],
        "nutrients": {
            "calories": "120.0000",
            "protein_g": "22.5000",
            "carbs_g": "0.0000",
            "fat_g": "2.6000",
            "sodium_mg": "45.0000",
        },
    },
    {
        "canonical_name": "Chicken breast, grilled",
        "external_id": "POPULAR-002",
        "country_code": "US",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["grilled chicken breast", "grilled chicken"],
        "nutrients": {
            "calories": "165.0000",
            "protein_g": "31.0000",
            "carbs_g": "0.0000",
            "fat_g": "3.6000",
            "sodium_mg": "74.0000",
        },
    },
    {
        "canonical_name": "Rotisserie chicken breast",
        "external_id": "POPULAR-003",
        "country_code": "US",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["rotisserie chicken", "roast chicken breast"],
        "nutrients": {
            "calories": "165.0000",
            "protein_g": "31.0000",
            "carbs_g": "0.0000",
            "fat_g": "3.6000",
            "sodium_mg": "350.0000",
        },
    },
    {
        "canonical_name": "Egg whites, boiled",
        "external_id": "POPULAR-004",
        "country_code": "US",
        "serving_description": "1 large egg white",
        "default_serving_g": "33.00",
        "verified": False,
        "aliases": ["boiled egg whites", "egg white"],
        "nutrients": {
            "calories": "52.0000",
            "protein_g": "10.9000",
            "carbs_g": "0.7000",
            "fat_g": "0.2000",
            "sodium_mg": "166.0000",
        },
    },
    {
        "canonical_name": "Brown rice, cooked",
        "external_id": "POPULAR-005",
        "country_code": "US",
        "serving_description": "1 cup cooked",
        "default_serving_g": "195.00",
        "verified": False,
        "aliases": ["cooked brown rice", "brown rice"],
        "nutrients": {
            "calories": "112.0000",
            "protein_g": "2.3000",
            "carbs_g": "23.5000",
            "fat_g": "0.8000",
            "fiber_g": "1.8000",
        },
    },
    {
        "canonical_name": "Basmati rice, cooked",
        "external_id": "POPULAR-006",
        "country_code": "IN",
        "serving_description": "1 cup cooked",
        "default_serving_g": "160.00",
        "verified": False,
        "aliases": ["basmati rice", "cooked basmati"],
        "nutrients": {
            "calories": "121.0000",
            "protein_g": "3.5000",
            "carbs_g": "25.2000",
            "fat_g": "0.4000",
            "fiber_g": "0.4000",
        },
    },
    {
        "canonical_name": "Roti",
        "external_id": "POPULAR-007",
        "country_code": "IN",
        "serving_description": "1 medium roti",
        "default_serving_g": "40.00",
        "verified": False,
        "aliases": ["roti", "phulka", "chapati"],
        "nutrients": {
            "calories": "260.0000",
            "protein_g": "8.7000",
            "carbs_g": "46.4000",
            "fat_g": "4.5000",
            "fiber_g": "6.7000",
        },
    },
    {
        "canonical_name": "Paratha, plain",
        "external_id": "POPULAR-008",
        "country_code": "IN",
        "serving_description": "1 paratha",
        "default_serving_g": "80.00",
        "verified": False,
        "aliases": ["plain paratha", "parantha"],
        "nutrients": {
            "calories": "326.0000",
            "protein_g": "7.0000",
            "carbs_g": "45.0000",
            "fat_g": "13.0000",
            "fiber_g": "5.0000",
        },
    },
    {
        "canonical_name": "Naan, plain",
        "external_id": "POPULAR-009",
        "country_code": "IN",
        "serving_description": "1 naan",
        "default_serving_g": "90.00",
        "verified": False,
        "aliases": ["naan", "plain naan"],
        "nutrients": {
            "calories": "310.0000",
            "protein_g": "9.0000",
            "carbs_g": "56.0000",
            "fat_g": "5.0000",
            "fiber_g": "2.5000",
        },
    },
    {
        "canonical_name": "Moong dal, cooked",
        "external_id": "POPULAR-010",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "180.00",
        "verified": False,
        "aliases": ["moong dal", "yellow dal"],
        "nutrients": {
            "calories": "105.0000",
            "protein_g": "7.0000",
            "carbs_g": "18.0000",
            "fat_g": "0.4000",
            "fiber_g": "7.0000",
        },
    },
    {
        "canonical_name": "Rajma curry",
        "external_id": "POPULAR-011",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "200.00",
        "verified": False,
        "aliases": ["rajma", "kidney bean curry"],
        "nutrients": {
            "calories": "127.0000",
            "protein_g": "7.0000",
            "carbs_g": "19.0000",
            "fat_g": "2.5000",
            "fiber_g": "6.0000",
        },
    },
    {
        "canonical_name": "Chole curry",
        "external_id": "POPULAR-012",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "200.00",
        "verified": False,
        "aliases": ["chole", "chickpea curry", "chana masala"],
        "nutrients": {
            "calories": "164.0000",
            "protein_g": "8.9000",
            "carbs_g": "27.4000",
            "fat_g": "2.6000",
            "fiber_g": "7.6000",
        },
    },
    {
        "canonical_name": "Paneer tikka",
        "external_id": "POPULAR-013",
        "country_code": "IN",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["paneer tikka", "grilled paneer"],
        "nutrients": {
            "calories": "278.0000",
            "protein_g": "18.0000",
            "carbs_g": "5.0000",
            "fat_g": "21.0000",
            "calcium_mg": "220.0000",
        },
    },
    {
        "canonical_name": "Idli",
        "external_id": "POPULAR-014",
        "country_code": "IN",
        "serving_description": "1 idli",
        "default_serving_g": "40.00",
        "verified": False,
        "aliases": ["idli", "steamed rice cake"],
        "nutrients": {
            "calories": "146.0000",
            "protein_g": "4.5000",
            "carbs_g": "30.0000",
            "fat_g": "0.7000",
            "fiber_g": "1.5000",
        },
    },
    {
        "canonical_name": "Dosa, plain",
        "external_id": "POPULAR-015",
        "country_code": "IN",
        "serving_description": "1 dosa",
        "default_serving_g": "97.00",
        "verified": False,
        "aliases": ["dosa", "plain dosa"],
        "nutrients": {
            "calories": "168.0000",
            "protein_g": "3.9000",
            "carbs_g": "29.0000",
            "fat_g": "3.7000",
            "fiber_g": "1.1000",
        },
    },
    {
        "canonical_name": "Sambar",
        "external_id": "POPULAR-016",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "200.00",
        "verified": False,
        "aliases": ["sambar", "sambhar"],
        "nutrients": {
            "calories": "65.0000",
            "protein_g": "3.5000",
            "carbs_g": "11.0000",
            "fat_g": "1.2000",
            "fiber_g": "3.5000",
        },
    },
    {
        "canonical_name": "Poha",
        "external_id": "POPULAR-017",
        "country_code": "IN",
        "serving_description": "1 plate",
        "default_serving_g": "180.00",
        "verified": False,
        "aliases": ["poha", "flattened rice poha"],
        "nutrients": {
            "calories": "180.0000",
            "protein_g": "3.5000",
            "carbs_g": "32.0000",
            "fat_g": "4.5000",
            "fiber_g": "2.0000",
        },
    },
    {
        "canonical_name": "Upma",
        "external_id": "POPULAR-018",
        "country_code": "IN",
        "serving_description": "1 plate",
        "default_serving_g": "180.00",
        "verified": False,
        "aliases": ["upma", "rava upma"],
        "nutrients": {
            "calories": "190.0000",
            "protein_g": "5.0000",
            "carbs_g": "30.0000",
            "fat_g": "5.5000",
            "fiber_g": "2.5000",
        },
    },
    {
        "canonical_name": "Chicken biryani",
        "external_id": "POPULAR-019",
        "country_code": "IN",
        "serving_description": "1 plate",
        "default_serving_g": "300.00",
        "verified": False,
        "aliases": ["chicken biryani", "biryani"],
        "nutrients": {
            "calories": "185.0000",
            "protein_g": "10.0000",
            "carbs_g": "22.0000",
            "fat_g": "6.0000",
            "fiber_g": "1.5000",
        },
    },
    {
        "canonical_name": "Salmon, cooked",
        "external_id": "POPULAR-020",
        "country_code": "US",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["salmon", "cooked salmon"],
        "nutrients": {
            "calories": "206.0000",
            "protein_g": "22.0000",
            "carbs_g": "0.0000",
            "fat_g": "12.0000",
            "sodium_mg": "59.0000",
        },
    },
    {
        "canonical_name": "Tuna, canned in water",
        "external_id": "POPULAR-021",
        "country_code": "US",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["tuna", "canned tuna"],
        "nutrients": {
            "calories": "116.0000",
            "protein_g": "25.5000",
            "carbs_g": "0.0000",
            "fat_g": "0.8000",
            "sodium_mg": "247.0000",
        },
    },
    {
        "canonical_name": "Greek yogurt, plain",
        "external_id": "POPULAR-022",
        "country_code": "US",
        "serving_description": "1 cup",
        "default_serving_g": "170.00",
        "verified": False,
        "aliases": ["greek yogurt", "plain greek yogurt"],
        "nutrients": {
            "calories": "73.0000",
            "protein_g": "10.0000",
            "carbs_g": "3.9000",
            "fat_g": "1.9000",
            "calcium_mg": "115.0000",
        },
    },
    {
        "canonical_name": "Quinoa, cooked",
        "external_id": "POPULAR-023",
        "country_code": "US",
        "serving_description": "1 cup cooked",
        "default_serving_g": "185.00",
        "verified": False,
        "aliases": ["quinoa", "cooked quinoa"],
        "nutrients": {
            "calories": "120.0000",
            "protein_g": "4.4000",
            "carbs_g": "21.3000",
            "fat_g": "1.9000",
            "fiber_g": "2.8000",
        },
    },
    {
        "canonical_name": "Sweet potato, boiled",
        "external_id": "POPULAR-024",
        "country_code": "US",
        "serving_description": "1 medium",
        "default_serving_g": "130.00",
        "verified": False,
        "aliases": ["sweet potato", "boiled sweet potato"],
        "nutrients": {
            "calories": "76.0000",
            "protein_g": "1.4000",
            "carbs_g": "17.7000",
            "fat_g": "0.1000",
            "fiber_g": "2.5000",
        },
    },
    {
        "canonical_name": "Broccoli, cooked",
        "external_id": "POPULAR-025",
        "country_code": "US",
        "serving_description": "1 cup",
        "default_serving_g": "156.00",
        "verified": False,
        "aliases": ["broccoli", "steamed broccoli"],
        "nutrients": {
            "calories": "35.0000",
            "protein_g": "2.4000",
            "carbs_g": "7.2000",
            "fat_g": "0.4000",
            "fiber_g": "3.3000",
            "vitamin_c_mg": "64.9000",
        },
    },
    {
        "canonical_name": "Mango",
        "external_id": "POPULAR-026",
        "country_code": "IN",
        "serving_description": "1 cup pieces",
        "default_serving_g": "165.00",
        "verified": False,
        "aliases": ["mango", "aam"],
        "nutrients": {
            "calories": "60.0000",
            "protein_g": "0.8000",
            "carbs_g": "15.0000",
            "fat_g": "0.4000",
            "fiber_g": "1.6000",
            "sugar_g": "13.7000",
        },
    },
    {
        "canonical_name": "Orange",
        "external_id": "POPULAR-027",
        "country_code": "US",
        "serving_description": "1 medium",
        "default_serving_g": "131.00",
        "verified": False,
        "aliases": ["orange", "santra"],
        "nutrients": {
            "calories": "47.0000",
            "protein_g": "0.9000",
            "carbs_g": "11.8000",
            "fat_g": "0.1000",
            "fiber_g": "2.4000",
            "vitamin_c_mg": "53.2000",
        },
    },
    {
        "canonical_name": "Peanuts, roasted",
        "external_id": "POPULAR-028",
        "country_code": "US",
        "serving_description": "1 oz",
        "default_serving_g": "28.00",
        "verified": False,
        "aliases": ["peanuts", "roasted peanuts", "moongfali"],
        "nutrients": {
            "calories": "585.0000",
            "protein_g": "24.4000",
            "carbs_g": "21.5000",
            "fat_g": "49.7000",
            "fiber_g": "8.0000",
        },
    },
    {
        "canonical_name": "Coffee with milk, no sugar",
        "external_id": "POPULAR-029",
        "country_code": "IN",
        "serving_description": "1 cup",
        "default_serving_g": "180.00",
        "verified": False,
        "aliases": ["milk coffee", "coffee"],
        "nutrients": {
            "calories": "32.0000",
            "protein_g": "1.7000",
            "carbs_g": "2.4000",
            "fat_g": "1.8000",
            "sugar_g": "2.5000",
        },
    },
    {
        "canonical_name": "Tea with milk, no sugar",
        "external_id": "POPULAR-030",
        "country_code": "IN",
        "serving_description": "1 cup",
        "default_serving_g": "180.00",
        "verified": False,
        "aliases": ["chai", "milk tea", "tea"],
        "nutrients": {
            "calories": "35.0000",
            "protein_g": "1.6000",
            "carbs_g": "2.8000",
            "fat_g": "1.7000",
            "sugar_g": "2.7000",
        },
    },
    {
        "canonical_name": "Banana",
        "external_id": "POPULAR-031",
        "country_code": "IN",
        "serving_description": "1 medium banana",
        "default_serving_g": "118.00",
        "verified": False,
        "aliases": ["banana", "kela"],
        "nutrients": {
            "calories": "89.0000",
            "protein_g": "1.1000",
            "carbs_g": "22.8000",
            "fat_g": "0.3000",
            "fiber_g": "2.6000",
            "sugar_g": "12.2000",
            "potassium_mg": "358.0000",
        },
    },
    {
        "canonical_name": "Apple",
        "external_id": "POPULAR-032",
        "country_code": "US",
        "serving_description": "1 medium apple",
        "default_serving_g": "182.00",
        "verified": False,
        "aliases": ["apple", "seb"],
        "nutrients": {
            "calories": "52.0000",
            "protein_g": "0.3000",
            "carbs_g": "13.8000",
            "fat_g": "0.2000",
            "fiber_g": "2.4000",
            "sugar_g": "10.4000",
        },
    },
    {
        "canonical_name": "Oats, cooked with water",
        "external_id": "POPULAR-033",
        "country_code": "US",
        "serving_description": "1 bowl",
        "default_serving_g": "234.00",
        "verified": False,
        "aliases": ["oats", "oatmeal", "plain oats"],
        "nutrients": {
            "calories": "71.0000",
            "protein_g": "2.5000",
            "carbs_g": "12.0000",
            "fat_g": "1.5000",
            "fiber_g": "1.7000",
        },
    },
    {
        "canonical_name": "Whey protein powder",
        "external_id": "POPULAR-034",
        "country_code": "US",
        "serving_description": "1 scoop",
        "default_serving_g": "30.00",
        "verified": False,
        "aliases": ["whey protein", "protein powder", "whey scoop"],
        "nutrients": {
            "calories": "400.0000",
            "protein_g": "80.0000",
            "carbs_g": "8.0000",
            "fat_g": "6.0000",
            "sugar_g": "4.0000",
            "sodium_mg": "200.0000",
        },
    },
    {
        "canonical_name": "Whole milk",
        "external_id": "POPULAR-035",
        "country_code": "IN",
        "serving_description": "1 cup",
        "default_serving_g": "244.00",
        "verified": False,
        "aliases": ["milk", "full cream milk", "whole milk"],
        "nutrients": {
            "calories": "61.0000",
            "protein_g": "3.2000",
            "carbs_g": "4.8000",
            "fat_g": "3.3000",
            "sugar_g": "5.1000",
            "calcium_mg": "113.0000",
            "sodium_mg": "43.0000",
        },
    },
    {
        "canonical_name": "Curd, plain",
        "external_id": "POPULAR-036",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "150.00",
        "verified": False,
        "aliases": ["curd", "dahi", "plain yogurt"],
        "nutrients": {
            "calories": "61.0000",
            "protein_g": "3.5000",
            "carbs_g": "4.7000",
            "fat_g": "3.3000",
            "sugar_g": "4.7000",
            "calcium_mg": "121.0000",
            "sodium_mg": "46.0000",
        },
    },
    {
        "canonical_name": "Paneer, full fat",
        "external_id": "POPULAR-037",
        "country_code": "IN",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["paneer", "cottage cheese"],
        "nutrients": {
            "calories": "265.0000",
            "protein_g": "18.3000",
            "carbs_g": "1.2000",
            "fat_g": "20.8000",
            "calcium_mg": "208.0000",
            "sodium_mg": "22.0000",
            "saturated_fat_g": "13.1000",
        },
    },
    {
        "canonical_name": "Tofu, firm",
        "external_id": "POPULAR-038",
        "country_code": "US",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["tofu", "firm tofu"],
        "nutrients": {
            "calories": "144.0000",
            "protein_g": "17.3000",
            "carbs_g": "2.8000",
            "fat_g": "8.7000",
            "fiber_g": "2.3000",
            "calcium_mg": "683.0000",
            "iron_mg": "2.7000",
        },
    },
    {
        "canonical_name": "Soy chunks, cooked",
        "external_id": "POPULAR-039",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["soya chunks", "soy chunks", "meal maker"],
        "nutrients": {
            "calories": "172.0000",
            "protein_g": "16.6000",
            "carbs_g": "9.9000",
            "fat_g": "0.5000",
            "fiber_g": "6.0000",
            "iron_mg": "3.9000",
        },
    },
    {
        "canonical_name": "Masoor dal, cooked",
        "external_id": "POPULAR-040",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "180.00",
        "verified": False,
        "aliases": ["masoor dal", "red lentil dal"],
        "nutrients": {
            "calories": "116.0000",
            "protein_g": "9.0000",
            "carbs_g": "20.1000",
            "fat_g": "0.4000",
            "fiber_g": "7.9000",
        },
    },
    {
        "canonical_name": "Dal makhani",
        "external_id": "POPULAR-041",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "200.00",
        "verified": False,
        "aliases": ["dal makhani", "black dal"],
        "nutrients": {
            "calories": "165.0000",
            "protein_g": "6.5000",
            "carbs_g": "17.0000",
            "fat_g": "8.0000",
            "fiber_g": "5.5000",
            "sodium_mg": "320.0000",
        },
    },
    {
        "canonical_name": "Chicken thigh, cooked",
        "external_id": "POPULAR-042",
        "country_code": "US",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["chicken thigh", "cooked chicken thigh"],
        "nutrients": {
            "calories": "209.0000",
            "protein_g": "26.0000",
            "carbs_g": "0.0000",
            "fat_g": "10.9000",
            "sodium_mg": "95.0000",
        },
    },
    {
        "canonical_name": "Fish curry",
        "external_id": "POPULAR-043",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "220.00",
        "verified": False,
        "aliases": ["fish curry", "machli curry"],
        "nutrients": {
            "calories": "132.0000",
            "protein_g": "14.0000",
            "carbs_g": "4.0000",
            "fat_g": "6.8000",
            "sodium_mg": "310.0000",
        },
    },
    {
        "canonical_name": "Mutton curry",
        "external_id": "POPULAR-044",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "220.00",
        "verified": False,
        "aliases": ["mutton curry", "lamb curry"],
        "nutrients": {
            "calories": "210.0000",
            "protein_g": "16.0000",
            "carbs_g": "5.0000",
            "fat_g": "14.0000",
            "sodium_mg": "340.0000",
        },
    },
    {
        "canonical_name": "Prawns, cooked",
        "external_id": "POPULAR-045",
        "country_code": "IN",
        "serving_description": "100 g",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["prawns", "shrimp", "cooked prawns"],
        "nutrients": {
            "calories": "99.0000",
            "protein_g": "24.0000",
            "carbs_g": "0.2000",
            "fat_g": "0.3000",
            "sodium_mg": "111.0000",
        },
    },
    {
        "canonical_name": "Boiled potato",
        "external_id": "POPULAR-046",
        "country_code": "IN",
        "serving_description": "1 medium potato",
        "default_serving_g": "150.00",
        "verified": False,
        "aliases": ["potato", "boiled potato", "aloo"],
        "nutrients": {
            "calories": "87.0000",
            "protein_g": "1.9000",
            "carbs_g": "20.1000",
            "fat_g": "0.1000",
            "fiber_g": "1.8000",
            "potassium_mg": "379.0000",
        },
    },
    {
        "canonical_name": "Mixed vegetable sabzi",
        "external_id": "POPULAR-047",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "180.00",
        "verified": False,
        "aliases": ["mixed veg", "vegetable sabzi", "sabzi"],
        "nutrients": {
            "calories": "96.0000",
            "protein_g": "2.5000",
            "carbs_g": "12.0000",
            "fat_g": "4.5000",
            "fiber_g": "4.0000",
            "sodium_mg": "260.0000",
        },
    },
    {
        "canonical_name": "Aloo gobi",
        "external_id": "POPULAR-048",
        "country_code": "IN",
        "serving_description": "1 bowl",
        "default_serving_g": "180.00",
        "verified": False,
        "aliases": ["aloo gobi", "potato cauliflower sabzi"],
        "nutrients": {
            "calories": "120.0000",
            "protein_g": "3.0000",
            "carbs_g": "18.0000",
            "fat_g": "4.0000",
            "fiber_g": "4.2000",
            "sodium_mg": "270.0000",
        },
    },
    {
        "canonical_name": "Spinach, cooked",
        "external_id": "POPULAR-049",
        "country_code": "IN",
        "serving_description": "1 cup",
        "default_serving_g": "180.00",
        "verified": False,
        "aliases": ["spinach", "palak", "cooked palak"],
        "nutrients": {
            "calories": "23.0000",
            "protein_g": "2.9000",
            "carbs_g": "3.6000",
            "fat_g": "0.4000",
            "fiber_g": "2.2000",
            "iron_mg": "2.7000",
            "vitamin_c_mg": "28.1000",
        },
    },
    {
        "canonical_name": "Cucumber",
        "external_id": "POPULAR-050",
        "country_code": "IN",
        "serving_description": "1 medium cucumber",
        "default_serving_g": "200.00",
        "verified": False,
        "aliases": ["cucumber", "kheera"],
        "nutrients": {
            "calories": "15.0000",
            "protein_g": "0.7000",
            "carbs_g": "3.6000",
            "fat_g": "0.1000",
            "fiber_g": "0.5000",
        },
    },
    {
        "canonical_name": "Tomato",
        "external_id": "POPULAR-051",
        "country_code": "IN",
        "serving_description": "1 medium tomato",
        "default_serving_g": "123.00",
        "verified": False,
        "aliases": ["tomato", "tamatar"],
        "nutrients": {
            "calories": "18.0000",
            "protein_g": "0.9000",
            "carbs_g": "3.9000",
            "fat_g": "0.2000",
            "fiber_g": "1.2000",
            "sugar_g": "2.6000",
        },
    },
    {
        "canonical_name": "Boiled egg, whole",
        "external_id": "POPULAR-052",
        "country_code": "US",
        "serving_description": "1 large egg",
        "default_serving_g": "50.00",
        "verified": False,
        "aliases": ["boiled egg", "egg", "whole egg"],
        "nutrients": {
            "calories": "155.0000",
            "protein_g": "12.6000",
            "carbs_g": "1.1000",
            "fat_g": "10.6000",
            "sodium_mg": "124.0000",
            "cholesterol_mg": "373.0000",
            "saturated_fat_g": "3.3000",
        },
    },
    {
        "canonical_name": "Omelette, plain",
        "external_id": "POPULAR-053",
        "country_code": "IN",
        "serving_description": "2 egg omelette",
        "default_serving_g": "120.00",
        "verified": False,
        "aliases": ["omelette", "omelet", "anda omelette"],
        "nutrients": {
            "calories": "154.0000",
            "protein_g": "11.0000",
            "carbs_g": "1.6000",
            "fat_g": "11.0000",
            "sodium_mg": "155.0000",
            "cholesterol_mg": "313.0000",
        },
    },
    {
        "canonical_name": "Whole wheat bread",
        "external_id": "POPULAR-054",
        "country_code": "US",
        "serving_description": "1 slice",
        "default_serving_g": "28.00",
        "verified": False,
        "aliases": ["brown bread", "whole wheat bread", "bread"],
        "nutrients": {
            "calories": "247.0000",
            "protein_g": "13.0000",
            "carbs_g": "41.0000",
            "fat_g": "4.2000",
            "fiber_g": "7.0000",
            "sodium_mg": "400.0000",
        },
    },
    {
        "canonical_name": "Peanut butter",
        "external_id": "POPULAR-055",
        "country_code": "US",
        "serving_description": "1 tablespoon",
        "default_serving_g": "16.00",
        "verified": False,
        "aliases": ["peanut butter", "groundnut butter"],
        "nutrients": {
            "calories": "588.0000",
            "protein_g": "25.1000",
            "carbs_g": "20.0000",
            "fat_g": "50.4000",
            "fiber_g": "6.0000",
            "sugar_g": "9.2000",
            "sodium_mg": "476.0000",
        },
    },
    {
        "canonical_name": "Almonds",
        "external_id": "POPULAR-056",
        "country_code": "US",
        "serving_description": "1 oz",
        "default_serving_g": "28.00",
        "verified": False,
        "aliases": ["almonds", "badam"],
        "nutrients": {
            "calories": "579.0000",
            "protein_g": "21.2000",
            "carbs_g": "21.6000",
            "fat_g": "49.9000",
            "fiber_g": "12.5000",
            "sugar_g": "4.4000",
            "calcium_mg": "269.0000",
        },
    },
    {
        "canonical_name": "Cashews",
        "external_id": "POPULAR-057",
        "country_code": "IN",
        "serving_description": "1 oz",
        "default_serving_g": "28.00",
        "verified": False,
        "aliases": ["cashew", "cashews", "kaju"],
        "nutrients": {
            "calories": "553.0000",
            "protein_g": "18.2000",
            "carbs_g": "30.2000",
            "fat_g": "43.9000",
            "fiber_g": "3.3000",
            "iron_mg": "6.7000",
        },
    },
    {
        "canonical_name": "Samosa",
        "external_id": "POPULAR-058",
        "country_code": "IN",
        "serving_description": "1 samosa",
        "default_serving_g": "100.00",
        "verified": False,
        "aliases": ["samosa", "aloo samosa"],
        "nutrients": {
            "calories": "308.0000",
            "protein_g": "5.0000",
            "carbs_g": "32.0000",
            "fat_g": "17.0000",
            "fiber_g": "3.0000",
            "sodium_mg": "420.0000",
        },
    },
    {
        "canonical_name": "Vada pav",
        "external_id": "POPULAR-059",
        "country_code": "IN",
        "serving_description": "1 vada pav",
        "default_serving_g": "150.00",
        "verified": False,
        "aliases": ["vada pav", "vada pao"],
        "nutrients": {
            "calories": "290.0000",
            "protein_g": "7.0000",
            "carbs_g": "42.0000",
            "fat_g": "10.0000",
            "fiber_g": "4.0000",
            "sodium_mg": "520.0000",
        },
    },
    {
        "canonical_name": "Pav bhaji",
        "external_id": "POPULAR-060",
        "country_code": "IN",
        "serving_description": "1 plate",
        "default_serving_g": "350.00",
        "verified": False,
        "aliases": ["pav bhaji", "paav bhaji"],
        "nutrients": {
            "calories": "150.0000",
            "protein_g": "4.0000",
            "carbs_g": "24.0000",
            "fat_g": "4.5000",
            "fiber_g": "4.0000",
            "sodium_mg": "390.0000",
        },
    },
    {
        "canonical_name": "Masala dosa",
        "external_id": "POPULAR-061",
        "country_code": "IN",
        "serving_description": "1 dosa",
        "default_serving_g": "150.00",
        "verified": False,
        "aliases": ["masala dosa", "dosa with potato"],
        "nutrients": {
            "calories": "196.0000",
            "protein_g": "4.4000",
            "carbs_g": "32.0000",
            "fat_g": "5.4000",
            "fiber_g": "2.3000",
            "sodium_mg": "330.0000",
        },
    },
    {
        "canonical_name": "Medu vada",
        "external_id": "POPULAR-062",
        "country_code": "IN",
        "serving_description": "1 vada",
        "default_serving_g": "60.00",
        "verified": False,
        "aliases": ["vada", "medu vada", "vada sambar"],
        "nutrients": {
            "calories": "334.0000",
            "protein_g": "12.0000",
            "carbs_g": "36.0000",
            "fat_g": "16.0000",
            "fiber_g": "8.0000",
            "sodium_mg": "320.0000",
        },
    },
    {
        "canonical_name": "Watermelon",
        "external_id": "POPULAR-063",
        "country_code": "IN",
        "serving_description": "1 cup diced",
        "default_serving_g": "152.00",
        "verified": False,
        "aliases": ["watermelon", "tarbooz"],
        "nutrients": {
            "calories": "30.0000",
            "protein_g": "0.6000",
            "carbs_g": "7.6000",
            "fat_g": "0.2000",
            "fiber_g": "0.4000",
            "sugar_g": "6.2000",
        },
    },
    {
        "canonical_name": "Papaya",
        "external_id": "POPULAR-064",
        "country_code": "IN",
        "serving_description": "1 cup pieces",
        "default_serving_g": "145.00",
        "verified": False,
        "aliases": ["papaya", "papita"],
        "nutrients": {
            "calories": "43.0000",
            "protein_g": "0.5000",
            "carbs_g": "10.8000",
            "fat_g": "0.3000",
            "fiber_g": "1.7000",
            "sugar_g": "7.8000",
            "vitamin_c_mg": "60.9000",
        },
    },
    {
        "canonical_name": "Lassi, sweet",
        "external_id": "POPULAR-065",
        "country_code": "IN",
        "serving_description": "1 glass",
        "default_serving_g": "250.00",
        "verified": False,
        "aliases": ["lassi", "sweet lassi"],
        "nutrients": {
            "calories": "88.0000",
            "protein_g": "3.3000",
            "carbs_g": "13.0000",
            "fat_g": "2.5000",
            "sugar_g": "12.0000",
            "calcium_mg": "120.0000",
        },
    },
    {
        "canonical_name": "Cheese slice",
        "external_id": "POPULAR-066",
        "country_code": "US",
        "serving_description": "1 slice",
        "default_serving_g": "21.00",
        "verified": False,
        "aliases": ["cheese", "cheese slice", "processed cheese"],
        "nutrients": {
            "calories": "353.0000",
            "protein_g": "21.0000",
            "carbs_g": "3.0000",
            "fat_g": "28.0000",
            "calcium_mg": "700.0000",
            "sodium_mg": "1450.0000",
            "saturated_fat_g": "18.0000",
        },
    },
    {
        "canonical_name": "Butter",
        "external_id": "POPULAR-067",
        "country_code": "US",
        "serving_description": "1 tablespoon",
        "default_serving_g": "14.00",
        "verified": False,
        "aliases": ["butter", "makkhan"],
        "nutrients": {
            "calories": "717.0000",
            "protein_g": "0.9000",
            "carbs_g": "0.1000",
            "fat_g": "81.1000",
            "saturated_fat_g": "51.4000",
            "sodium_mg": "11.0000",
        },
    },
    {
        "canonical_name": "Olive oil",
        "external_id": "POPULAR-068",
        "country_code": "US",
        "serving_description": "1 tablespoon",
        "default_serving_g": "14.00",
        "verified": False,
        "aliases": ["olive oil", "oil"],
        "nutrients": {
            "calories": "884.0000",
            "protein_g": "0.0000",
            "carbs_g": "0.0000",
            "fat_g": "100.0000",
            "saturated_fat_g": "13.8000",
            "sodium_mg": "2.0000",
        },
    },
    {
        "canonical_name": "Avocado",
        "external_id": "POPULAR-069",
        "country_code": "US",
        "serving_description": "1 medium avocado",
        "default_serving_g": "150.00",
        "verified": False,
        "aliases": ["avocado"],
        "nutrients": {
            "calories": "160.0000",
            "protein_g": "2.0000",
            "carbs_g": "8.5000",
            "fat_g": "14.7000",
            "fiber_g": "6.7000",
            "sugar_g": "0.7000",
            "potassium_mg": "485.0000",
        },
    },
    {
        "canonical_name": "Cooked white rice",
        "external_id": "POPULAR-070",
        "country_code": "IN",
        "serving_description": "1 cup cooked",
        "default_serving_g": "158.00",
        "verified": False,
        "aliases": ["white rice", "rice", "cooked rice", "steamed rice"],
        "nutrients": {
            "calories": "130.0000",
            "protein_g": "2.7000",
            "carbs_g": "28.2000",
            "fat_g": "0.3000",
            "fiber_g": "0.4000",
            "sugar_g": "0.1000",
            "sodium_mg": "1.0000",
        },
    },
]


POPULAR_FOODS.extend(
    [
        {
            "canonical_name": "Chapati, whole wheat",
            "external_id": "POPULAR-071",
            "country_code": "IN",
            "serving_description": "1 medium chapati",
            "default_serving_g": "40.00",
            "verified": False,
            "aliases": ["chapati", "roti", "phulka", "whole wheat chapati"],
            "nutrients": {
                "calories": "260.0000",
                "protein_g": "8.7000",
                "carbs_g": "46.4000",
                "fat_g": "4.5000",
                "fiber_g": "6.7000",
                "iron_mg": "3.2000",
            },
        },
        {
            "canonical_name": "Tandoori chicken",
            "external_id": "POPULAR-072",
            "country_code": "IN",
            "serving_description": "1 piece",
            "default_serving_g": "120.00",
            "verified": False,
            "aliases": ["tandoori chicken", "roasted chicken tikka"],
            "nutrients": {
                "calories": "180.0000",
                "protein_g": "27.0000",
                "carbs_g": "2.5000",
                "fat_g": "6.5000",
                "sodium_mg": "390.0000",
                "saturated_fat_g": "1.8000",
            },
        },
        {
            "canonical_name": "Chicken curry",
            "external_id": "POPULAR-073",
            "country_code": "IN",
            "serving_description": "1 bowl",
            "default_serving_g": "220.00",
            "verified": False,
            "aliases": ["chicken curry", "chicken gravy", "murgh curry"],
            "nutrients": {
                "calories": "160.0000",
                "protein_g": "16.5000",
                "carbs_g": "4.8000",
                "fat_g": "8.4000",
                "fiber_g": "1.0000",
                "sodium_mg": "360.0000",
                "saturated_fat_g": "2.4000",
            },
        },
        {
            "canonical_name": "Butter chicken",
            "external_id": "POPULAR-074",
            "country_code": "IN",
            "serving_description": "1 bowl",
            "default_serving_g": "240.00",
            "verified": False,
            "aliases": ["butter chicken", "murgh makhani"],
            "nutrients": {
                "calories": "220.0000",
                "protein_g": "15.0000",
                "carbs_g": "7.5000",
                "fat_g": "14.5000",
                "sugar_g": "3.2000",
                "sodium_mg": "440.0000",
                "saturated_fat_g": "6.1000",
            },
        },
        {
            "canonical_name": "Egg bhurji",
            "external_id": "POPULAR-075",
            "country_code": "IN",
            "serving_description": "1 plate",
            "default_serving_g": "150.00",
            "verified": False,
            "aliases": ["egg bhurji", "anda bhurji", "scrambled egg indian"],
            "nutrients": {
                "calories": "185.0000",
                "protein_g": "11.5000",
                "carbs_g": "3.6000",
                "fat_g": "13.5000",
                "sodium_mg": "260.0000",
                "cholesterol_mg": "310.0000",
                "saturated_fat_g": "3.8000",
            },
        },
        {
            "canonical_name": "Scrambled eggs",
            "external_id": "POPULAR-076",
            "country_code": "US",
            "serving_description": "2 eggs",
            "default_serving_g": "120.00",
            "verified": False,
            "aliases": ["scrambled eggs", "scrambled egg"],
            "nutrients": {
                "calories": "166.0000",
                "protein_g": "10.0000",
                "carbs_g": "2.2000",
                "fat_g": "12.8000",
                "sodium_mg": "170.0000",
                "cholesterol_mg": "310.0000",
                "saturated_fat_g": "4.0000",
            },
        },
        {
            "canonical_name": "Khichdi",
            "external_id": "POPULAR-077",
            "country_code": "IN",
            "serving_description": "1 bowl",
            "default_serving_g": "250.00",
            "verified": False,
            "aliases": ["khichdi", "moong dal khichdi", "dal rice khichdi"],
            "nutrients": {
                "calories": "118.0000",
                "protein_g": "4.2000",
                "carbs_g": "20.5000",
                "fat_g": "2.2000",
                "fiber_g": "2.7000",
                "sodium_mg": "230.0000",
            },
        },
        {
            "canonical_name": "Vegetable pulao",
            "external_id": "POPULAR-078",
            "country_code": "IN",
            "serving_description": "1 plate",
            "default_serving_g": "250.00",
            "verified": False,
            "aliases": ["vegetable pulao", "veg pulao", "pulao"],
            "nutrients": {
                "calories": "145.0000",
                "protein_g": "3.2000",
                "carbs_g": "25.5000",
                "fat_g": "3.5000",
                "fiber_g": "2.2000",
                "sodium_mg": "290.0000",
            },
        },
        {
            "canonical_name": "Curd rice",
            "external_id": "POPULAR-079",
            "country_code": "IN",
            "serving_description": "1 bowl",
            "default_serving_g": "250.00",
            "verified": False,
            "aliases": ["curd rice", "dahi rice", "yogurt rice"],
            "nutrients": {
                "calories": "112.0000",
                "protein_g": "3.5000",
                "carbs_g": "18.0000",
                "fat_g": "2.7000",
                "sugar_g": "2.8000",
                "calcium_mg": "85.0000",
                "sodium_mg": "180.0000",
            },
        },
        {
            "canonical_name": "Jeera rice",
            "external_id": "POPULAR-080",
            "country_code": "IN",
            "serving_description": "1 cup",
            "default_serving_g": "180.00",
            "verified": False,
            "aliases": ["jeera rice", "cumin rice"],
            "nutrients": {
                "calories": "150.0000",
                "protein_g": "2.7000",
                "carbs_g": "28.0000",
                "fat_g": "3.2000",
                "fiber_g": "0.6000",
                "sodium_mg": "190.0000",
            },
        },
        {
            "canonical_name": "Besan chilla",
            "external_id": "POPULAR-081",
            "country_code": "IN",
            "serving_description": "1 chilla",
            "default_serving_g": "90.00",
            "verified": False,
            "aliases": ["besan chilla", "besan cheela", "gram flour pancake"],
            "nutrients": {
                "calories": "190.0000",
                "protein_g": "9.0000",
                "carbs_g": "22.0000",
                "fat_g": "7.0000",
                "fiber_g": "5.0000",
                "iron_mg": "2.6000",
            },
        },
        {
            "canonical_name": "Dhokla",
            "external_id": "POPULAR-082",
            "country_code": "IN",
            "serving_description": "4 pieces",
            "default_serving_g": "120.00",
            "verified": False,
            "aliases": ["dhokla", "khaman dhokla", "khaman"],
            "nutrients": {
                "calories": "160.0000",
                "protein_g": "6.0000",
                "carbs_g": "26.0000",
                "fat_g": "3.2000",
                "fiber_g": "3.5000",
                "sodium_mg": "380.0000",
            },
        },
        {
            "canonical_name": "Uttapam",
            "external_id": "POPULAR-083",
            "country_code": "IN",
            "serving_description": "1 uttapam",
            "default_serving_g": "150.00",
            "verified": False,
            "aliases": ["uttapam", "uttappa", "onion uttapam"],
            "nutrients": {
                "calories": "180.0000",
                "protein_g": "4.5000",
                "carbs_g": "30.0000",
                "fat_g": "4.8000",
                "fiber_g": "2.4000",
                "sodium_mg": "330.0000",
            },
        },
        {
            "canonical_name": "Rava dosa",
            "external_id": "POPULAR-084",
            "country_code": "IN",
            "serving_description": "1 dosa",
            "default_serving_g": "120.00",
            "verified": False,
            "aliases": ["rava dosa", "semolina dosa"],
            "nutrients": {
                "calories": "190.0000",
                "protein_g": "4.1000",
                "carbs_g": "34.0000",
                "fat_g": "4.2000",
                "fiber_g": "1.5000",
                "sodium_mg": "300.0000",
            },
        },
        {
            "canonical_name": "Coconut chutney",
            "external_id": "POPULAR-085",
            "country_code": "IN",
            "serving_description": "2 tablespoons",
            "default_serving_g": "30.00",
            "verified": False,
            "aliases": ["coconut chutney", "nariyal chutney"],
            "nutrients": {
                "calories": "185.0000",
                "protein_g": "2.6000",
                "carbs_g": "8.4000",
                "fat_g": "16.0000",
                "fiber_g": "5.0000",
                "sodium_mg": "210.0000",
                "saturated_fat_g": "13.0000",
            },
        },
        {
            "canonical_name": "Green chutney",
            "external_id": "POPULAR-086",
            "country_code": "IN",
            "serving_description": "2 tablespoons",
            "default_serving_g": "30.00",
            "verified": False,
            "aliases": ["green chutney", "mint chutney", "coriander chutney"],
            "nutrients": {
                "calories": "45.0000",
                "protein_g": "1.8000",
                "carbs_g": "8.0000",
                "fat_g": "1.1000",
                "fiber_g": "2.7000",
                "sodium_mg": "260.0000",
            },
        },
        {
            "canonical_name": "Boiled black chana",
            "external_id": "POPULAR-087",
            "country_code": "IN",
            "serving_description": "1 bowl",
            "default_serving_g": "180.00",
            "verified": False,
            "aliases": ["black chana", "kala chana", "boiled chana"],
            "nutrients": {
                "calories": "164.0000",
                "protein_g": "8.9000",
                "carbs_g": "27.4000",
                "fat_g": "2.6000",
                "fiber_g": "7.6000",
                "iron_mg": "2.9000",
            },
        },
        {
            "canonical_name": "Moong sprouts",
            "external_id": "POPULAR-088",
            "country_code": "IN",
            "serving_description": "1 cup",
            "default_serving_g": "100.00",
            "verified": False,
            "aliases": ["moong sprouts", "sprouts", "sprouted moong"],
            "nutrients": {
                "calories": "30.0000",
                "protein_g": "3.0000",
                "carbs_g": "6.0000",
                "fat_g": "0.2000",
                "fiber_g": "1.8000",
                "vitamin_c_mg": "13.0000",
            },
        },
        {
            "canonical_name": "Sprouts salad",
            "external_id": "POPULAR-089",
            "country_code": "IN",
            "serving_description": "1 bowl",
            "default_serving_g": "180.00",
            "verified": False,
            "aliases": ["sprouts salad", "mixed sprouts salad"],
            "nutrients": {
                "calories": "70.0000",
                "protein_g": "5.0000",
                "carbs_g": "12.0000",
                "fat_g": "1.0000",
                "fiber_g": "4.0000",
                "sodium_mg": "120.0000",
            },
        },
        {
            "canonical_name": "Chicken sandwich",
            "external_id": "POPULAR-090",
            "country_code": "IN",
            "serving_description": "1 sandwich",
            "default_serving_g": "180.00",
            "verified": False,
            "aliases": ["chicken sandwich", "grilled chicken sandwich"],
            "nutrients": {
                "calories": "230.0000",
                "protein_g": "15.0000",
                "carbs_g": "25.0000",
                "fat_g": "8.0000",
                "fiber_g": "3.0000",
                "sodium_mg": "520.0000",
                "saturated_fat_g": "2.2000",
            },
        },
        {
            "canonical_name": "Paneer bhurji",
            "external_id": "POPULAR-091",
            "country_code": "IN",
            "serving_description": "1 bowl",
            "default_serving_g": "180.00",
            "verified": False,
            "aliases": ["paneer bhurji", "paneer scramble"],
            "nutrients": {
                "calories": "245.0000",
                "protein_g": "14.0000",
                "carbs_g": "6.5000",
                "fat_g": "18.0000",
                "fiber_g": "1.5000",
                "calcium_mg": "210.0000",
                "sodium_mg": "310.0000",
                "saturated_fat_g": "10.8000",
            },
        },
        {
            "canonical_name": "Palak paneer",
            "external_id": "POPULAR-092",
            "country_code": "IN",
            "serving_description": "1 bowl",
            "default_serving_g": "220.00",
            "verified": False,
            "aliases": ["palak paneer", "spinach paneer"],
            "nutrients": {
                "calories": "190.0000",
                "protein_g": "10.0000",
                "carbs_g": "7.0000",
                "fat_g": "13.0000",
                "fiber_g": "2.8000",
                "calcium_mg": "210.0000",
                "iron_mg": "2.5000",
                "sodium_mg": "360.0000",
            },
        },
        {
            "canonical_name": "Matar paneer",
            "external_id": "POPULAR-093",
            "country_code": "IN",
            "serving_description": "1 bowl",
            "default_serving_g": "220.00",
            "verified": False,
            "aliases": ["matar paneer", "mutter paneer", "peas paneer"],
            "nutrients": {
                "calories": "180.0000",
                "protein_g": "9.0000",
                "carbs_g": "10.0000",
                "fat_g": "11.5000",
                "fiber_g": "3.5000",
                "calcium_mg": "180.0000",
                "sodium_mg": "340.0000",
            },
        },
        {
            "canonical_name": "Protein shake with milk",
            "external_id": "POPULAR-094",
            "country_code": "US",
            "serving_description": "1 shaker",
            "default_serving_g": "300.00",
            "verified": False,
            "aliases": ["protein shake", "whey with milk", "milk protein shake"],
            "nutrients": {
                "calories": "135.0000",
                "protein_g": "16.0000",
                "carbs_g": "8.5000",
                "fat_g": "3.2000",
                "sugar_g": "6.5000",
                "calcium_mg": "180.0000",
                "sodium_mg": "115.0000",
            },
        },
        {
            "canonical_name": "Low-fat milk",
            "external_id": "POPULAR-095",
            "country_code": "IN",
            "serving_description": "1 cup",
            "default_serving_g": "244.00",
            "verified": False,
            "aliases": ["low fat milk", "toned milk"],
            "nutrients": {
                "calories": "50.0000",
                "protein_g": "3.4000",
                "carbs_g": "4.9000",
                "fat_g": "1.9000",
                "sugar_g": "5.0000",
                "calcium_mg": "120.0000",
                "sodium_mg": "45.0000",
            },
        },
        {
            "canonical_name": "Skim milk",
            "external_id": "POPULAR-096",
            "country_code": "US",
            "serving_description": "1 cup",
            "default_serving_g": "245.00",
            "verified": False,
            "aliases": ["skim milk", "fat free milk"],
            "nutrients": {
                "calories": "34.0000",
                "protein_g": "3.4000",
                "carbs_g": "5.0000",
                "fat_g": "0.1000",
                "sugar_g": "5.0000",
                "calcium_mg": "122.0000",
                "sodium_mg": "42.0000",
            },
        },
        {
            "canonical_name": "Greek yogurt, nonfat",
            "external_id": "POPULAR-097",
            "country_code": "US",
            "serving_description": "1 cup",
            "default_serving_g": "170.00",
            "verified": False,
            "aliases": ["nonfat greek yogurt", "fat free greek yogurt"],
            "nutrients": {
                "calories": "59.0000",
                "protein_g": "10.3000",
                "carbs_g": "3.6000",
                "fat_g": "0.4000",
                "sugar_g": "3.2000",
                "calcium_mg": "110.0000",
                "sodium_mg": "36.0000",
            },
        },
        {
            "canonical_name": "Chicken sausage",
            "external_id": "POPULAR-098",
            "country_code": "US",
            "serving_description": "1 sausage",
            "default_serving_g": "75.00",
            "verified": False,
            "aliases": ["chicken sausage", "sausage"],
            "nutrients": {
                "calories": "180.0000",
                "protein_g": "16.0000",
                "carbs_g": "2.0000",
                "fat_g": "12.0000",
                "sodium_mg": "760.0000",
                "cholesterol_mg": "70.0000",
                "saturated_fat_g": "3.2000",
            },
        },
        {
            "canonical_name": "Boiled corn",
            "external_id": "POPULAR-099",
            "country_code": "IN",
            "serving_description": "1 cup",
            "default_serving_g": "165.00",
            "verified": False,
            "aliases": ["corn", "sweet corn", "boiled corn", "bhutta"],
            "nutrients": {
                "calories": "96.0000",
                "protein_g": "3.4000",
                "carbs_g": "21.0000",
                "fat_g": "1.5000",
                "fiber_g": "2.4000",
                "sugar_g": "4.5000",
                "potassium_mg": "218.0000",
            },
        },
        {
            "canonical_name": "Green peas, cooked",
            "external_id": "POPULAR-100",
            "country_code": "IN",
            "serving_description": "1 cup",
            "default_serving_g": "160.00",
            "verified": False,
            "aliases": ["green peas", "matar", "cooked peas"],
            "nutrients": {
                "calories": "84.0000",
                "protein_g": "5.4000",
                "carbs_g": "15.6000",
                "fat_g": "0.2000",
                "fiber_g": "5.5000",
                "sugar_g": "5.9000",
                "potassium_mg": "271.0000",
            },
        },
        {
            "canonical_name": "Carrot",
            "external_id": "POPULAR-101",
            "country_code": "IN",
            "serving_description": "1 medium carrot",
            "default_serving_g": "61.00",
            "verified": False,
            "aliases": ["carrot", "gajar"],
            "nutrients": {
                "calories": "41.0000",
                "protein_g": "0.9000",
                "carbs_g": "9.6000",
                "fat_g": "0.2000",
                "fiber_g": "2.8000",
                "sugar_g": "4.7000",
                "potassium_mg": "320.0000",
                "vitamin_a_mcg": "835.0000",
            },
        },
        {
            "canonical_name": "Beetroot, boiled",
            "external_id": "POPULAR-102",
            "country_code": "IN",
            "serving_description": "1 cup",
            "default_serving_g": "170.00",
            "verified": False,
            "aliases": ["beetroot", "beet", "chukandar"],
            "nutrients": {
                "calories": "44.0000",
                "protein_g": "1.7000",
                "carbs_g": "10.0000",
                "fat_g": "0.2000",
                "fiber_g": "2.0000",
                "sugar_g": "8.0000",
                "potassium_mg": "305.0000",
            },
        },
        {
            "canonical_name": "Dates",
            "external_id": "POPULAR-103",
            "country_code": "IN",
            "serving_description": "2 dates",
            "default_serving_g": "48.00",
            "verified": False,
            "aliases": ["dates", "khajoor", "date fruit"],
            "nutrients": {
                "calories": "277.0000",
                "protein_g": "1.8000",
                "carbs_g": "75.0000",
                "fat_g": "0.2000",
                "fiber_g": "6.7000",
                "sugar_g": "66.5000",
                "potassium_mg": "696.0000",
            },
        },
        {
            "canonical_name": "Raisins",
            "external_id": "POPULAR-104",
            "country_code": "IN",
            "serving_description": "1 small handful",
            "default_serving_g": "40.00",
            "verified": False,
            "aliases": ["raisins", "kishmish"],
            "nutrients": {
                "calories": "299.0000",
                "protein_g": "3.1000",
                "carbs_g": "79.0000",
                "fat_g": "0.5000",
                "fiber_g": "3.7000",
                "sugar_g": "59.0000",
                "potassium_mg": "749.0000",
            },
        },
        {
            "canonical_name": "Instant noodles masala",
            "external_id": "POPULAR-105",
            "country_code": "IN",
            "serving_description": "1 packet cooked",
            "default_serving_g": "210.00",
            "verified": False,
            "aliases": ["instant noodles", "masala noodles", "maggi style noodles"],
            "nutrients": {
                "calories": "210.0000",
                "protein_g": "5.0000",
                "carbs_g": "32.0000",
                "fat_g": "7.0000",
                "fiber_g": "2.0000",
                "sodium_mg": "820.0000",
                "saturated_fat_g": "3.2000",
            },
        },
        {
            "canonical_name": "Bhel puri",
            "external_id": "POPULAR-106",
            "country_code": "IN",
            "serving_description": "1 plate",
            "default_serving_g": "180.00",
            "verified": False,
            "aliases": ["bhel puri", "bhel", "chaat"],
            "nutrients": {
                "calories": "190.0000",
                "protein_g": "5.0000",
                "carbs_g": "34.0000",
                "fat_g": "4.0000",
                "fiber_g": "4.0000",
                "sugar_g": "6.0000",
                "sodium_mg": "520.0000",
            },
        },
        {
            "canonical_name": "Pani puri",
            "external_id": "POPULAR-107",
            "country_code": "IN",
            "serving_description": "6 pieces",
            "default_serving_g": "120.00",
            "verified": False,
            "aliases": ["pani puri", "golgappa", "puchka"],
            "nutrients": {
                "calories": "225.0000",
                "protein_g": "5.0000",
                "carbs_g": "38.0000",
                "fat_g": "6.0000",
                "fiber_g": "4.0000",
                "sodium_mg": "650.0000",
            },
        },
        {
            "canonical_name": "Sev puri",
            "external_id": "POPULAR-108",
            "country_code": "IN",
            "serving_description": "1 plate",
            "default_serving_g": "160.00",
            "verified": False,
            "aliases": ["sev puri", "sev poori"],
            "nutrients": {
                "calories": "240.0000",
                "protein_g": "6.0000",
                "carbs_g": "36.0000",
                "fat_g": "8.0000",
                "fiber_g": "4.0000",
                "sodium_mg": "620.0000",
            },
        },
        {
            "canonical_name": "Jowar roti",
            "external_id": "POPULAR-109",
            "country_code": "IN",
            "serving_description": "1 roti",
            "default_serving_g": "55.00",
            "verified": False,
            "aliases": ["jowar roti", "jowar bhakri", "sorghum roti"],
            "nutrients": {
                "calories": "330.0000",
                "protein_g": "10.4000",
                "carbs_g": "72.6000",
                "fat_g": "1.9000",
                "fiber_g": "6.3000",
                "iron_mg": "4.1000",
            },
        },
        {
            "canonical_name": "Bajra roti",
            "external_id": "POPULAR-110",
            "country_code": "IN",
            "serving_description": "1 roti",
            "default_serving_g": "55.00",
            "verified": False,
            "aliases": ["bajra roti", "bajra bhakri", "pearl millet roti"],
            "nutrients": {
                "calories": "361.0000",
                "protein_g": "11.6000",
                "carbs_g": "67.0000",
                "fat_g": "5.0000",
                "fiber_g": "8.5000",
                "iron_mg": "8.0000",
            },
        },
    ]
)


class Command(BaseCommand):
    help = "Seed a larger local friends-beta food catalog for daily testing."

    def handle(self, *args, **options):
        seed_core_reference_data()
        source = get_manual_sample_source()
        job = create_import_job(source, file_name="seed_popular_foods")
        result = import_json_food_records(
            POPULAR_FOODS,
            source,
            default_food_type=Food.FoodType.GENERIC,
        )
        finish_import_job(job, result)
        self.stdout.write(
            self.style.SUCCESS(
                "Seeded popular foods: "
                f"{result.rows_created} created, {result.rows_updated} updated, "
                f"{len(result.errors or [])} errors."
            )
        )
