# Generated by Django 5.2.15 on 2026-06-28 19:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=80)),
                ("external_user_id", models.CharField(blank=True, max_length=180)),
                (
                    "token_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference to encrypted secret storage; never store raw tokens here.",
                        max_length=255,
                    ),
                ),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("provider",),
                "indexes": [
                    models.Index(
                        fields=["user", "provider", "is_active"],
                        name="integration_user_id_d58a53_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "provider", "external_user_id"),
                        name="unique_integration_account_per_provider_user",
                    )
                ],
            },
        ),
    ]
