# Generated by Django 5.2.15 on 2026-06-28 21:06

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0004_favoritefood"),
        ("meals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mealitem",
            name="meal",
        ),
        migrations.RemoveField(
            model_name="mealitem",
            name="food",
        ),
        migrations.RemoveField(
            model_name="mealitem",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="mealitem",
            name="user",
        ),
        migrations.CreateModel(
            name="DailyNutritionSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "calories_kcal",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "protein_g",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "carbs_g",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "fat_g",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "fiber_g",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "sugar_g",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "sodium_mg",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("micronutrients", models.JSONField(blank=True, default=dict)),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="MealLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                            ("pre_workout", "Pre-workout"),
                            ("post_workout", "Post-workout"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date", "meal_type", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="MealLogItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("grams", "Grams"),
                            ("serving", "Serving"),
                            ("piece", "Piece"),
                            ("ml", "Milliliter"),
                            ("cup", "Cup"),
                            ("tbsp", "Tablespoon"),
                            ("tsp", "Teaspoon"),
                            ("custom", "Custom"),
                        ],
                        default="grams",
                        max_length=32,
                    ),
                ),
                (
                    "grams_calculated",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "calories_kcal",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("macros_snapshot", models.JSONField(blank=True, default=dict)),
                ("nutrients_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "source_confidence",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("user_confirmed", models.BooleanField(default=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meal_log_items",
                        to="foods.food",
                    ),
                ),
                (
                    "meal_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="meals.meallog",
                    ),
                ),
                (
                    "serving",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meal_log_items",
                        to="foods.foodserving",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.DeleteModel(
            name="MealEntry",
        ),
        migrations.DeleteModel(
            name="MealItem",
        ),
        migrations.AddIndex(
            model_name="dailynutritionsummary",
            index=models.Index(
                fields=["user", "date"], name="meals_daily_user_id_b64491_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailynutritionsummary",
            constraint=models.UniqueConstraint(
                fields=("user", "date"),
                name="unique_daily_nutrition_summary_per_user_date",
            ),
        ),
        migrations.AddIndex(
            model_name="meallog",
            index=models.Index(
                fields=["user", "date", "meal_type"],
                name="meals_meall_user_id_5c3053_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meallog",
            index=models.Index(
                fields=["user", "is_favorite"], name="meals_meall_user_id_5dc366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meallogitem",
            index=models.Index(
                fields=["user", "meal_log"], name="meals_meall_user_id_866364_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meallogitem",
            index=models.Index(
                fields=["user", "food"], name="meals_meall_user_id_84813a_idx"
            ),
        ),
    ]
