# Generated by Django 5.2.15 on 2026-06-28 19:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyNutritionSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary_date", models.DateField()),
                (
                    "calories_kcal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "protein_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "carbohydrates_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fiber_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "sugar_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "sodium_mg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("water_ml", models.PositiveIntegerField(default=0)),
                ("insights", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-summary_date",),
                "indexes": [
                    models.Index(
                        fields=["user", "summary_date"],
                        name="analytics_d_user_id_c409c6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "summary_date"),
                        name="unique_daily_nutrition_summary_per_user",
                    )
                ],
            },
        ),
    ]
