# Generated by Django 5.2.15 on 2026-06-29 12:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("nutrition", "Nutrition"),
                            ("habit", "Habit"),
                            ("weight", "Weight"),
                            ("recovery", "Recovery"),
                            ("adherence", "Adherence"),
                            ("safety", "Safety"),
                            ("custom", "Custom"),
                        ],
                        default="nutrition",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dismissed", "Dismissed"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="rules_engine",
                        help_text="rules_engine, ai_estimate, coach_admin, or integration name.",
                        max_length=64,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("related_date", models.DateField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "status", "created_at"],
                        name="analytics_c_user_id_676ee6_idx",
                    ),
                    models.Index(
                        fields=["user", "insight_type", "related_date"],
                        name="analytics_c_user_id_56ca6d_idx",
                    ),
                ],
            },
        ),
    ]
