# Generated by Django 5.2.15 on 2026-06-28 19:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("calories", "Calories"),
                            ("protein", "Protein"),
                            ("water", "Water"),
                            ("weight", "Weight"),
                            ("body_metric", "Body metric"),
                            ("habit", "Habit"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_value", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(max_length=32)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("status", "end_date", "title"),
                "indexes": [
                    models.Index(
                        fields=["user", "goal_type", "status"],
                        name="goals_goal_user_id_274e53_idx",
                    )
                ],
            },
        ),
    ]
