# Generated by Django 5.2.15 on 2026-06-29 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dailychecklisttask",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_habit__isnull", False)),
                fields=("user", "source_habit", "task_date"),
                name="unique_generated_task_per_user_habit_day",
            ),
        ),
    ]
