# Generated by Django 5.2.15 on 2026-06-29 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0002_dailychecklisttask_unique_generated_task_per_user_habit_day"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("nutrition", "Nutrition"),
                            ("workout", "Workout"),
                            ("water", "Water"),
                            ("sleep", "Sleep"),
                            ("mindfulness", "Mindfulness"),
                            ("medicine", "Medicine"),
                            ("study", "Study"),
                            ("productivity", "Productivity"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("default_target_count", models.PositiveIntegerField(default=1)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("checkbox", "Checkbox"),
                            ("glasses", "Glasses"),
                            ("minutes", "Minutes"),
                            ("grams", "Grams"),
                            ("steps", "Steps"),
                            ("pages", "Pages"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("icon", models.CharField(default="check", max_length=64)),
            ],
            options={
                "ordering": ("category", "title"),
            },
        ),
        migrations.CreateModel(
            name="HabitCheck",
            fields=[],
            options={
                "verbose_name": "habit check",
                "verbose_name_plural": "habit checks",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("habits.habitcheckin",),
        ),
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ("sort_order", "title")},
        ),
        migrations.RemoveIndex(
            model_name="habit",
            name="habits_habi_user_id_f3c6c0_idx",
        ),
        migrations.AddField(
            model_name="habit",
            name="category",
            field=models.CharField(
                choices=[
                    ("nutrition", "Nutrition"),
                    ("workout", "Workout"),
                    ("water", "Water"),
                    ("sleep", "Sleep"),
                    ("mindfulness", "Mindfulness"),
                    ("medicine", "Medicine"),
                    ("study", "Study"),
                    ("productivity", "Productivity"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="color",
            field=models.CharField(default="#22C55E", max_length=32),
        ),
        migrations.AddField(
            model_name="habit",
            name="days_of_week",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="habit",
            name="icon",
            field=models.CharField(default="check", max_length=64),
        ),
        migrations.AddField(
            model_name="habit",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("custom_days", "Custom days"),
                ],
                default="daily",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="habit",
            name="unit",
            field=models.CharField(
                choices=[
                    ("checkbox", "Checkbox"),
                    ("glasses", "Glasses"),
                    ("minutes", "Minutes"),
                    ("grams", "Grams"),
                    ("steps", "Steps"),
                    ("pages", "Pages"),
                    ("custom", "Custom"),
                ],
                default="checkbox",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="habitcheckin",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "is_active", "sort_order"],
                name="habits_habi_user_id_b32106_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "category", "is_active"],
                name="habits_habi_user_id_e0b0e2_idx",
            ),
        ),
    ]
