# Generated by Django 5.2.15 on 2026-06-28 21:21

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0004_favoritefood"),
        ("photos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photomealsuggestion",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="photomealsuggestion",
            name="food",
        ),
        migrations.RemoveField(
            model_name="photomealsuggestion",
            name="user",
        ),
        migrations.CreateModel(
            name="PhotoAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="photo-analyses/%Y/%m/%d/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("needs_review", "Needs review"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=32,
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("meal_photo", "Meal photo"),
                            ("nutrition_label", "Nutrition label"),
                            ("barcode_photo", "Barcode photo"),
                        ],
                        default="meal_photo",
                        max_length=32,
                    ),
                ),
                (
                    "ai_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("google_vision", "Google Vision"),
                            ("local_model", "Local model"),
                            ("manual", "Manual"),
                        ],
                        default="local_model",
                        max_length=32,
                    ),
                ),
                ("raw_ai_response", models.JSONField(blank=True, default=dict)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NutritionLabelScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_name", models.CharField(blank=True, max_length=255)),
                ("brand", models.CharField(blank=True, max_length=255)),
                ("serving_size", models.CharField(blank=True, max_length=120)),
                ("barcode", models.CharField(blank=True, max_length=64)),
                ("parsed_nutrients", models.JSONField(blank=True, default=dict)),
                ("ingredients_text", models.TextField(blank=True)),
                ("allergens", models.JSONField(blank=True, default=list)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "photo_analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_label_scan",
                        to="photos.photoanalysis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhotoDetectedFood",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detected_name", models.CharField(max_length=255)),
                (
                    "quantity_estimate",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                ("unit_estimate", models.CharField(default="serving", max_length=32)),
                (
                    "grams_estimate",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("bounding_box", models.JSONField(blank=True, default=dict)),
                ("user_confirmed", models.BooleanField(default=False)),
                ("user_corrected_name", models.CharField(blank=True, max_length=255)),
                (
                    "user_corrected_grams",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("reasoning_short", models.CharField(blank=True, max_length=255)),
                (
                    "matched_food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo_detections",
                        to="foods.food",
                    ),
                ),
                (
                    "photo_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_foods",
                        to="photos.photoanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ("-confidence_score", "detected_name"),
            },
        ),
        migrations.DeleteModel(
            name="PhotoMealAnalysis",
        ),
        migrations.DeleteModel(
            name="PhotoMealSuggestion",
        ),
        migrations.AddIndex(
            model_name="photoanalysis",
            index=models.Index(
                fields=["user", "status", "created_at"],
                name="photos_phot_user_id_99f930_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="photoanalysis",
            index=models.Index(
                fields=["user", "analysis_type", "created_at"],
                name="photos_phot_user_id_b321d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nutritionlabelscan",
            index=models.Index(
                fields=["barcode"], name="photos_nutr_barcode_d24956_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nutritionlabelscan",
            index=models.Index(
                fields=["product_name", "brand"], name="photos_nutr_product_c23741_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photodetectedfood",
            index=models.Index(
                fields=["photo_analysis", "user_confirmed"],
                name="photos_phot_photo_a_8c3af1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="photodetectedfood",
            index=models.Index(
                fields=["matched_food"], name="photos_phot_matched_7f78a6_idx"
            ),
        ),
    ]
