# Generated by Django 5.2.15 on 2026-06-29 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0004_favoritefood"),
        ("photos", "0002_remove_photomealsuggestion_analysis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photodetectedfood",
            name="added_manually",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="correction_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="count_confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="grams_per_unit_estimate",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="is_user_corrected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="max_total_grams_estimate",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="min_total_grams_estimate",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="normalized_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="nutrition_preview_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="portion_confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="quantity_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("piece", "Piece"),
                    ("egg", "Egg"),
                    ("slice", "Slice"),
                    ("bowl", "Bowl"),
                    ("cup", "Cup"),
                    ("glass", "Glass"),
                    ("tablespoon", "Tablespoon"),
                    ("teaspoon", "Teaspoon"),
                    ("serving", "Serving"),
                    ("gram", "Gram"),
                    ("ml", "Milliliter"),
                    ("handful", "Handful"),
                    ("scoop", "Scoop"),
                    ("packet", "Packet"),
                    ("custom", "Custom"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="quantity_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="total_grams_estimate",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="user_quantity_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("piece", "Piece"),
                    ("egg", "Egg"),
                    ("slice", "Slice"),
                    ("bowl", "Bowl"),
                    ("cup", "Cup"),
                    ("glass", "Glass"),
                    ("tablespoon", "Tablespoon"),
                    ("teaspoon", "Teaspoon"),
                    ("serving", "Serving"),
                    ("gram", "Gram"),
                    ("ml", "Milliliter"),
                    ("handful", "Handful"),
                    ("scoop", "Scoop"),
                    ("packet", "Packet"),
                    ("custom", "Custom"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="user_quantity_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="photodetectedfood",
            name="user_total_grams",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="photodetectedfood",
            index=models.Index(
                fields=["photo_analysis", "is_removed"],
                name="photos_phot_photo_a_9857d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="photodetectedfood",
            index=models.Index(
                fields=["normalized_name"], name="photos_phot_normali_b25046_idx"
            ),
        ),
    ]
