# Generated by Django 5.2.15 on 2026-06-28 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="allergies",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(default="IN", max_length=2),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="dietary_preference",
            field=models.CharField(
                choices=[
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                    ("eggetarian", "Eggetarian"),
                    ("non_vegetarian", "Non vegetarian"),
                    ("jain", "Jain"),
                    ("keto", "Keto"),
                    ("high_protein", "High protein"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="disliked_foods",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender_optional",
            field=models.CharField(
                blank=True,
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                    ("non_binary", "Non-binary"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("lose_weight", "Lose weight"),
                    ("maintain", "Maintain"),
                    ("gain_muscle", "Gain muscle"),
                    ("improve_health", "Improve health"),
                ],
                default="improve_health",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="has_completed_onboarding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_step",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="target_weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(default="UTC", max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["user", "has_completed_onboarding"],
                name="profiles_us_user_id_63adf4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["country", "dietary_preference"],
                name="profiles_us_country_3e77ee_idx",
            ),
        ),
    ]
