# Generated by Django 5.2.15 on 2026-06-28 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0004_favoritefood"),
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="preparation_note",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="quantity_g",
        ),
        migrations.AddField(
            model_name="recipe",
            name="cuisine",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recipe",
            name="total_weight_g",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="recipe",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("shared_family", "Shared family"),
                    ("public", "Public"),
                ],
                default="private",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="grams_calculated",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="serving",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipe_ingredients",
                to="foods.foodserving",
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("grams", "Grams"),
                    ("serving", "Serving"),
                    ("piece", "Piece"),
                    ("ml", "Milliliter"),
                    ("cup", "Cup"),
                    ("tbsp", "Tablespoon"),
                    ("tsp", "Teaspoon"),
                    ("custom", "Custom"),
                ],
                default="grams",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipe_ingredients",
                to="foods.food",
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["user", "visibility"], name="recipes_rec_user_id_dda706_idx"
            ),
        ),
    ]
